# Generated by Django 4.0.3 on 2022-12-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_customer_phone_number_alter_sales_automobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sale_price',
            new_name='sales_price',
        ),
        migrations.RenameField(
            model_name='salesperson',
            old_name='employee_name',
            new_name='sales_person',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='color',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='href',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='year',
            field=models.PositiveSmallIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
