# Generated by Django 4.0.3 on 2022-12-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_remove_automobilevo_color_remove_automobilevo_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='href',
            new_name='import_href',
        ),
    ]
