# Generated by Django 4.0.3 on 2022-12-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_automobilevo_color_remove_automobilevo_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date_time',
        ),
    ]
