# Generated by Django 4.0.3 on 2022-12-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rename_date_appointment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='owner',
            new_name='customer_name',
        ),
    ]
